SELECT
    O_ORDERKEY,
    O_CUSTKEY,
    O_ORDERDATE,
    O_ORDERPRIORITY,
    O_ORDERSTATUS,
    CASE 
      WHEN O_ORDERSTATUS = 'F' THEN 'FINALIZED'
      WHEN O_ORDERSTATUS = 'O' THEN 'OPEN'
      WHEN O_ORDERSTATUS = 'P' THEN 'PENDING'
      ELSE 'UNKNOWN'
    END AS ORDER_STATUS_MEANING,
        O_TOTALPRICE,
    CASE 
      WHEN O_TOTALPRICE >= 100000 THEN 'HIGH VALUE ORDER'
      WHEN O_TOTALPRICE BETWEEN 50000 AND 99999 THEN 'MEDIUM VALUE ORDER'
      ELSE 'LOW VALUE ORDER'
    END AS PRICE_CATEGORY,
    O_SHIPPRIORITY,
    DATEDIFF(DAY, O_ORDERDATE, CURRENT_DATE) AS ORDER_AGE_DAYS,
    TRIM(O_COMMENT) AS CLEAN_COMMENT,
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS