SELECT
    L_ORDERKEY,
    L_PARTKEY,
    L_SUPPKEY,
    L_LINENUMBER,
    L_QUANTITY,
    L_EXTENDEDPRICE,
    L_DISCOUNT,
    L_TAX,
    ROUND(L_EXTENDEDPRICE * (1 - L_DISCOUNT), 2) AS NET_REVENUE,
    ROUND(L_EXTENDEDPRICE * L_TAX, 2) AS TOTAL_TAX_AMOUNT,
    L_RETURNFLAG,
    CASE 
      WHEN L_RETURNFLAG = 'R' THEN 'RETURNED'
      WHEN L_RETURNFLAG = 'A' THEN 'ACCEPTED'
      ELSE 'NO RETURN'
    END AS RETURN_REASON,
    L_COMMITDATE,
    L_RECEIPTDATE,
    CASE 
      WHEN L_RECEIPTDATE > L_COMMITDATE THEN 'YES'
      ELSE 'NO'
    END AS IS_DELAYED,
    TRIM(L_COMMENT) AS CLEAN_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM